namespace Forum.Application.DTOs.Category;

/// <summary>
/// DTO for creating a new category. Contains only the Name field since
/// CategoryId is auto-generated by the database. Only admins can create categories.
/// </summary>
public record CreateCategoryDto(string Name);